# Generated by Django 4.2.5 on 2023-09-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_book_id_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.booktitle",
            ),
        ),
    ]
