# Generated by Django 4.2.5 on 2023-09-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_books",
                to="books.booktitle",
            ),
        ),
    ]
