# Generated by Django 4.2.5 on 2023-09-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("#0", "rented"),
                            ("#1", "returned"),
                            ("#2", "lost"),
                            ("#3", "delayed"),
                        ],
                        default="#1",
                        max_length=2,
                    ),
                ),
                (
                    "rented_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the book was rented",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time when the book is due"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time when the book was returned"
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
