# Generated by Django 4.2.5 on 2023-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0002_alter_rental_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="returned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the book was returned",
                null=True,
            ),
        ),
    ]
