# Generated by Django 4.2.5 on 2023-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_alter_rental_returned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="rented_at",
            field=models.DateTimeField(
                help_text="Date and time when the book was rented"
            ),
        ),
    ]
